export { loadConfig, saveConfig, clearConfig, tokenPrefix, getCloudConfigPath } from './auth'
export type { CloudConfig } from './auth'
export { resolveProjectIdentity, normalizeProjectSlug } from './identity'
export { track, flush, deliverEvents, isEnabled } from './events'
export type { EventPayload } from './events'
export { syncSkills } from './skills-sync'
export type { SyncResult } from './skills-sync'
export { kiroScan } from './scanner'
export { installKiroWatcher, uninstallKiroWatcher, watcherStatus } from './watcher'
export { enrollProject } from './enrollment'
export { login, logout, status as cloudStatus } from './login'
